mongo:
  ip : 127.0.0.1
  port : 27017
  database : kakaobot

device:
  uuid : 0a/jpfWtteQEqJuVWp1gdIkb/yhnANuYmxkXCFpcSB2Uu0XU5wuTkJ3gBRxFRRpyKI2406Xbyp+GVP7LcKOG4Q==
  name : iPhone
  email : sonaapi17@gmail.com
  password : maple.support

rabbitmq:
  ip: 127.0.0.1
  port: 5672
  exchange: rainbow