mongo:
  ip : 127.0.0.1
  port : 27017
  database : kakaobot

device:
  uuid : your-uuid
  name : your-name
  email : your-email
  password : your-password

rabbitmq:
  ip: 127.0.0.1
  port: 5672
  exchange: rainbow